### ISSUE TITLE
Not an issue but a question of it's workings.

### ISSUE THREAD

**Issue by ghost** [Xpl0itU/USBHide#1]
Sorry if this is an inconvenience asking here btw, but is this operating in a way similar to U-Stealth? I vaguely remember something about it corrupting a part of the MBD (master boot drive) to where it's still usable but the Wii U isnt able to detect it's use. Is it the same in this case? Or done differently.

(too lazy to look over .cpp file lol sorry)

**Comment by Xpl0itU** [comment]
Yes, it does the same thing

**Comment by ghost** [comment]
Alright thank you for clarification.
